### ISSUE TITLE
ECE calibration in scoring.py seems to be wrong

### ISSUE THREAD

**Issue by ghost** [JonathanWenger/pycalib#4]
Hi, 
the calibrated_acc in ECE evaluation is not an averaged prediction, which seems to be inconsistent with your ECE definition as given in the paper Sec. 3.1 (9). Could you please clarify this point? Many thanks in advance.

**Comment by JonathanWenger** [comment]
Good catch. Thinking in terms of reliability diagrams, this difference is whether you are measuring how much the accuracy in each bin differs from the diagonal (confidence = accuracy) or from the average accuracy in the bin. If the distribution of samples in a bin is close to uniform this is the same, if it is very skewed then not. However their difference is bounded by half the bin size. In practice this difference should be negligible unless for a hypothetical calibration method which uses a similar binning to the ECE and produces calibrated confidence estimates which always get pushed to one of the edges of the binning.

I'll update the code to match the definition in the paper once I get the chance.

**Comment by Jordy-VL** [comment]
The implementation is not correct for fully accurate predictions, where it still factors in some miscalibration error...
